## PyTorch Fundamentals
Resource Notebook:https://learnpytorch.io

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors
Creating tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html



In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[1,3,5],[2,3,7]])
matrix

tensor([[1, 3, 5],
        [2, 3, 7]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
# Tensors
t = torch.tensor([[[1,2],[1,2]],[[2,3],[5,6]]])
t

tensor([[[1, 2],
         [1, 2]],

        [[2, 3],
         [5, 6]]])

In [ ]:
t.ndim

3

In [ ]:
t.shape

torch.Size([2, 2, 2])

## Random Tensors
Why random tensors?

Randorm tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers --> look at data --> update random numbers

In [ ]:
# Create a random tensor of shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8414, 0.5059, 0.0477, 0.7443],
        [0.1038, 0.7499, 0.2700, 0.1048],
        [0.1330, 0.5574, 0.2727, 0.5583]])

In [ ]:
random_tensor1 = torch.rand(3,2,4)
random_tensor1

tensor([[[0.8174, 0.5406, 0.4341, 0.5392],
         [0.0148, 0.6446, 0.9557, 0.3579]],

        [[0.0711, 0.6673, 0.1367, 0.6621],
         [0.4680, 0.1702, 0.0444, 0.4825]],

        [[0.2519, 0.9339, 0.2857, 0.4852],
         [0.6997, 0.7090, 0.6493, 0.3425]]])

In [ ]:
random_image = torch.rand(3,244,244)
random_image

tensor([[[0.0724, 0.4899, 0.0044,  ..., 0.5591, 0.5759, 0.2602],
         [0.5952, 0.3535, 0.3025,  ..., 0.6324, 0.8535, 0.0122],
         [0.3099, 0.0225, 0.7532,  ..., 0.1103, 0.0760, 0.7028],
         ...,
         [0.8594, 0.2276, 0.9515,  ..., 0.3223, 0.4314, 0.6217],
         [0.7288, 0.4550, 0.4144,  ..., 0.9707, 0.1190, 0.4078],
         [0.2463, 0.0328, 0.0294,  ..., 0.0763, 0.6341, 0.5436]],

        [[0.3739, 0.8610, 0.6171,  ..., 0.6432, 0.1788, 0.9928],
         [0.3682, 0.1592, 0.3859,  ..., 0.8431, 0.4716, 0.7555],
         [0.1574, 0.2306, 0.7155,  ..., 0.9801, 0.7834, 0.3017],
         ...,
         [0.2994, 0.6233, 0.2368,  ..., 0.0309, 0.4770, 0.3162],
         [0.1721, 0.0226, 0.7191,  ..., 0.5573, 0.2571, 0.4768],
         [0.0877, 0.7603, 0.0836,  ..., 0.1229, 0.1033, 0.4070]],

        [[0.1624, 0.0070, 0.6822,  ..., 0.4433, 0.0021, 0.0470],
         [0.7048, 0.3913, 0.9466,  ..., 0.1312, 0.9662, 0.4362],
         [0.7828, 0.4430, 0.3407,  ..., 0.0029, 0.2117, 0.

## Zeros and ones

In [ ]:
# Creating tensor of zeros
zeros = torch.zeros((2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Creating tensor of ones
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
One_to_Ten = torch.arange(1,11)

In [ ]:
torch.arange(1,1000,50)

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [ ]:
# Creating tensor like
ten_like = torch.zeros_like(input=One_to_Ten)
ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data types

Note : Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([i for i in range(1,6)],
                               dtype = torch.float16,
                               device = None,
                               requires_grad= False)
float_32_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float16)

In [ ]:
float_32_tensor.ndim

1

In [ ]:
float_32_tensor.shape

torch.Size([5])

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([i for i in range(1,6)],dtype= torch.int16)
int_16_tensor = torch.tensor([i for i in range(5,11)],dtype=torch.int16)

In [ ]:
print(int_16_tensor)
print(int_32_tensor)

tensor([ 5,  6,  7,  8,  9, 10], dtype=torch.int16)
tensor([1, 2, 3, 4, 5], dtype=torch.int16)


In [ ]:
# find out some details about some tensor
some_tensor = torch.rand((3,2,4))
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[[0.2543, 0.3388, 0.4419, 0.5660],
         [0.5167, 0.8161, 0.7664, 0.7731]],

        [[0.5712, 0.2693, 0.8945, 0.9976],
         [0.9029, 0.8007, 0.0753, 0.8499]],

        [[0.7701, 0.4208, 0.9328, 0.2730],
         [0.0775, 0.8393, 0.2032, 0.6529]]])
Datatype of tensor: torch.float32
shape of tensor : torch.Size([3, 2, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations includes:
* Addition
* Subtraction
* Multiplication (Element-wise)
* Division
*Matrix multiplication

In [ ]:
tensor = torch.tensor([ i for i in range(1,5)])
tensor += 10
tensor

tensor([11, 12, 13, 14])

In [ ]:
tensor *= 10
tensor

tensor([110, 120, 130, 140])

In [ ]:
torch.mul(tensor,10)

tensor([1100, 1200, 1300, 1400])

In [ ]:
torch.add(tensor,52)

tensor([162, 172, 182, 192])

In [ ]:
a = torch.rand((2,4))
b = torch.rand((4,7))
c = torch.matmul(a,b)


In [ ]:
a

tensor([[0.9373, 0.7010, 0.7495, 0.7502],
        [0.3076, 0.1822, 0.0779, 0.1842]])

In [ ]:
b

tensor([[0.8405, 0.8143, 0.5884, 0.8830, 0.7982, 0.6288, 0.6105],
        [0.4559, 0.4140, 0.1051, 0.9773, 0.2393, 0.2237, 0.5656],
        [0.8907, 0.6576, 0.8823, 0.4379, 0.4726, 0.9668, 0.3165],
        [0.6641, 0.1748, 0.1396, 0.0410, 0.3277, 0.0242, 0.4425]])

In [ ]:
c

tensor([[2.2731, 1.6774, 1.3912, 1.8716, 1.5159, 1.4890, 1.5378],
        [0.5334, 0.4094, 0.2946, 0.4914, 0.3863, 0.3140, 0.3970]])

In [ ]:
## Adjusting size for Matrix Multiplication

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])
tensor_B = torch.tensor([[7,8],
                         [8,9],
                         [6,7]])
tensor_A.shape,tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# To fix our Tensor shape , we can manipulate one of the tensors using Transpose

In [ ]:
tensor_B

tensor([[7, 8],
        [8, 9],
        [6, 7]])

In [ ]:
tensor_B_T = tensor_B.T
tensor_B_T

tensor([[7, 8, 6],
        [8, 9, 7]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[23, 26, 20],
        [38, 43, 33],
        [53, 60, 46]])

In [ ]:
#Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(1,200,20)
x

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181])

In [ ]:
torch.min(x)


tensor(1)

In [ ]:
torch.max(x)

tensor(181)

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(91.), tensor(91.))

In [ ]:
torch.sum(x)

tensor(910)

## Finding the positional min and max

In [ ]:
x

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all 1 dimensions form a Tensor
* Unsqueeze - add a 1 dimension to a target tensor
*permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
# let's create a tensor
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# ADD an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
# ADD an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

RuntimeError: shape '[1, 9]' is invalid for input of size 24

In [ ]:
# ADD an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped

RuntimeError: shape '[3, 3]' is invalid for input of size 24

In [ ]:
z =x.view(1,9)
z,z.shape

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original )
z[:,0]=5
z,x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x],dim=0)
x_stacked

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]])

In [ ]:
# torch.squeeze - removes 1 dimensions form tensor
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
yy = torch.squeeze(x,0)
yy.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
# torch.unsqueeze - adds a single dimension to a target tensor at a specific dim(dimension)
y.unsqueeze(3)


tensor([[[[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]]]])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange the axis (or dim)  order
x_permuted = x_original.permute(2,0,1)  # shifts axis 0 -> 1, 1-> 2, 2->0
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x_original[0,0,0]

tensor(0.7027)

In [ ]:
x_original[0,0,0] = 999
x_original[0,0,0],x_permuted[0,0,0]

(tensor(999.), tensor(999.))

In [ ]:
# indexing with PyTorch is similar to indexing with Numpy

In [ ]:
# create a tensor
x = torch.arange(1,25).reshape(2,3,4)
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [ ]:
x[0],x[0][0],x[0][0][0]

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([1, 2, 3, 4]),
 tensor(1))

In [ ]:
x[0][2][2]

tensor(11)

In [ ]:
# you can also use ":" to select all of a target dimesions
x[:,0],x[:,1],x[:,2]

(tensor([[ 1,  2,  3,  4],
         [13, 14, 15, 16]]),
 tensor([[ 5,  6,  7,  8],
         [17, 18, 19, 20]]),
 tensor([[ 9, 10, 11, 12],
         [21, 22, 23, 24]]))

In [ ]:
# create a tensor
x = torch.arange(1,25).reshape(2,3,4)
x


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [ ]:
x[1:,1:2,1:3]

tensor([[[18, 19]]])

## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
And Because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch -> torch.from_numpy(ndarray)
* PyTorch tensor --> NumPy --> tensor.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

In [ ]:
array = np.arange(1,25).reshape(2,3,4)
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
tensor = torch.from_numpy(array)
tensor

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [ ]:
array.dtype,tensor.dtype

(dtype('int64'), torch.int64)

In [ ]:
array += 1
array,tensor

(array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]))

## Reproducibilty (trying to take random out of random)

In short how a neural network learns:


start with random numbers -> tensor operations -> update random numbers to try and make them learn from the data -> again --> again

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A,random_tensor_B,random_tensor_A==random_tensor_B

(tensor([[0.8441, 0.5691, 0.0535, 0.8512],
         [0.1027, 0.2677, 0.4801, 0.7770],
         [0.0570, 0.2887, 0.7754, 0.5436]]),
 tensor([[0.8371, 0.7677, 0.3976, 0.5485],
         [0.7637, 0.6018, 0.3902, 0.7033],
         [0.9269, 0.1221, 0.4261, 0.6182]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
# Let's make some random but reproducible tensors
# set the random seed
SEED = 32
torch.manual_seed(SEED)
rand_A = torch.rand(3,4)
torch.manual_seed(SEED)
rand_B = torch.rand(3,4)
rand_A,rand_B,rand_A == rand_B

(tensor([[0.8757, 0.2721, 0.4141, 0.7857],
         [0.1130, 0.5793, 0.6481, 0.0229],
         [0.5874, 0.3254, 0.9485, 0.5219]]),
 tensor([[0.8757, 0.2721, 0.4141, 0.7857],
         [0.1130, 0.5793, 0.6481, 0.0229],
         [0.5874, 0.3254, 0.9485, 0.5219]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## Running tensors and PyTorch objects on the GPU (making faster computings)


GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything .

## 1. Getting a GPU
1. Easiest - use a Google coolab
--> change runtime environment --> select GPU --> then OK.


2.. # check for the GPU access wtih PyTorch


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# setUp device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

3. Putting tensors (and models ) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computings.


In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([i for i in range(1,10)]).reshape(3,3)
tensor,tensor.device

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 device(type='cpu'))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')

In [ ]:
# Moving tensors back to the GPU, can't transform it to NumPy
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])