# Numpy

In [ ]:
import numpy as np
import random

In [ ]:
arr = np.array([random.randint(1,10) for i in range(36)])
arr

array([ 4,  3,  5,  1,  6, 10,  2,  1,  8,  9,  3, 10,  2,  6,  7,  6,  6,
        9,  2,  3,  6,  9,  8, 10, 10,  9, 10,  5,  6,  8,  5,  5, 10, 10,
        7,  9])

In [ ]:
arr = arr.reshape((6,6))
arr

array([[ 4,  3,  5,  1,  6, 10],
       [ 2,  1,  8,  9,  3, 10],
       [ 2,  6,  7,  6,  6,  9],
       [ 2,  3,  6,  9,  8, 10],
       [10,  9, 10,  5,  6,  8],
       [ 5,  5, 10, 10,  7,  9]])

In [ ]:
kernel_size = 2
dup = arr.view()
dup

array([[ 4,  3,  5,  1,  6, 10],
       [ 2,  1,  8,  9,  3, 10],
       [ 2,  6,  7,  6,  6,  9],
       [ 2,  3,  6,  9,  8, 10],
       [10,  9, 10,  5,  6,  8],
       [ 5,  5, 10, 10,  7,  9]])

In [ ]:
kernel = dup[(dup.shape[0]//2)-(kernel_size//2):(dup.shape[0]//2)-(kernel_size//2)+ kernel_size,(dup.shape[0]//2)-(kernel_size//2):(dup.shape[0]//2)-(kernel_size//2)+ kernel_size]
kernel

array([[7, 6],
       [6, 9]])

In [ ]:
dup

array([[ 4,  3,  5,  1,  6, 10],
       [ 2,  1,  8,  9,  3, 10],
       [10,  9, 10,  5,  6,  8],
       [ 2,  3,  6,  9,  8, 10],
       [ 2,  6,  7,  6,  6,  9],
       [ 5,  5, 10, 10,  7,  9]])

In [ ]:
for i in range(dup.shape[0]):
  dup[2][i],dup[4][i]=dup[4][i],dup[2][i]

dup

array([[ 4,  3,  5,  1,  6, 10],
       [ 2,  1,  8,  9,  3, 10],
       [ 2,  6,  7,  6,  6,  9],
       [ 2,  3,  6,  9,  8, 10],
       [10,  9, 10,  5,  6,  8],
       [ 5,  5, 10, 10,  7,  9]])

TypeError: slice indices must be integers or None or have an __index__ method