In [ ]:
# fibonacci series
n = int(input("Enter n:"))
a=0
b=1
for i in range(n):
  c=a+b
  print(a)
  a=b
  b=c

Enter n:9
0
1
1
2
3
5
8
13
21


In [ ]:
# Multiple list in single list
#l = list(map(int,input().split()))
l = [1,3,[4,5],6]
res=[]
for i in range(len(l)):
  t=l[i]
  if(t is list):
    for j in range(len(t)):
      res.append(t[j])
  else:
    res.append(l[i])
print(res)


[1, 3, [4, 5], 6]


In [ ]:
# remove duplicates
l=[2,3,4,4,4,5,2,3]
r=[]
for i in l:
  if i not in r:
    r.append(i)
print(r)


[2, 3, 4, 5]


In [ ]:
l=[2,3,3,4,4,2,4]
d=dict()
for i in l:
  if i not in d.keys():
    d[i]=1
  else:
    d[i]=d[i]+1
print(d)

{2: 2, 3: 2, 4: 3}


In [ ]:
l=[0,0,2,4,4,0,0,0]

In [ ]:
count = list(filter(lambda x: x==4,l ))
count

[4, 4, 4]

In [ ]:
l=[1,0,1,1,0,0,0]
occ = list(map(lambdax : x if x==0 else 0,l))
occ

[0, 1, 0, 0, 1, 1, 1]

In [ ]:
file = open("/content/input (1).txt",'r')
file

<_io.TextIOWrapper name='/content/input (1).txt' mode='r' encoding='UTF-8'>

In [ ]:
content = file.read()

In [ ]:
content

'this is ml lab.\nml is future.'

In [ ]:
text = content.split('\n')
text

['this is ml lab.', 'ml is future.']

In [ ]:
words = []
for i in text:
  word = i.split( )
  words.extend(word)
words

['this', 'is', 'ml', 'lab.', 'ml', 'is', 'future.']

In [ ]:
uniword = set(words)
occ = dict()
for i in uniword:
  occ[i]=words.count(i)
occ

{'is': 2, 'future.': 1, 'this': 1, 'ml': 2, 'lab.': 1}

In [ ]:
# anagram
a="secure"
b="rescue"
a=''.join(sorted(a))
b=''.join(sorted(b))
a,b
if a==b:
  print("yes")
else:
  print("No")

yes


In [ ]:
import numpy as np

In [ ]:
import random

In [ ]:
n= int(input("Enter n:"))
arr = np.array([[random.randint(1,10) for i in range(n)]for i in range(n)])
arr

Enter n:5


array([[ 7,  5,  9,  1,  1],
       [ 8,  2,  8, 10,  6],
       [ 1,  2,  9,  3,  9],
       [ 6, 10,  8,  4,  1],
       [ 4,  8,  4,  1,  5]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
for i in range(n):
  print(arr[i][i])


7
2
9
4
5


In [ ]:
# wrong
diagonal = list(filter(lambda x : arr[i][i] , [i for i in range(n)]))
diagonal

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-76-8164c080172e>, line 2)

In [ ]:
# array board casting
n= int(input("Enter n:"))
arr1 = np.array([[random.randint(1,10) for i in range(n)]for i in range(n)])
arr2 = np.array([random.randint(1,10) for i in range(n)])
arr1,arr2

Enter n:3


(array([[ 4,  4, 10],
        [ 5,  7,  3],
        [ 5,  2,  4]]),
 array([7, 1, 2]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
n= int(input("Enter n:"))
arr1 = np.array([[random.randint(1,10) for i in range(n)]for i in range(n)])


Enter n:6


In [ ]:
arr1


array([[ 8,  7,  5,  7,  4,  7],
       [ 4,  9,  4,  3,  6,  9],
       [ 9,  8,  1,  9,  1,  3],
       [ 2,  7,  3,  7,  1, 10],
       [10,  2,  9,  7,  4, 10],
       [ 8, 10, 10,  9,  3,  4]])

In [ ]:
arr1.shape[0]

6

In [ ]:
kernel = arr1[2:arr1.shape[0]-2]
kernel

array([[ 9,  8,  1,  9,  1,  3],
       [ 2,  7,  3,  7,  1, 10]])