In [ ]:
import numpy as np

# creating numpy/ n-d array
1. Using np.array() // 1D and 2D
2. Using np.zeros()/ones/empty/random()
3. Using np.arange()
4. Using np.linspace()
5. Using np.copy()
6. Using np.Identity()


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr6 = np.arange(1,6)
arr6

array([1, 2, 3, 4, 5])

In [ ]:
arr7 = np.linspace(1,9,3)
arr7

array([1., 5., 9.])

In [ ]:
arr8 = np.copy(arr2)
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr9 = np.empty((2,3))
arr9

array([[4.97823125e-310, 0.00000000e+000, 6.80418313e-310],
       [7.20535013e+159, 1.42853560e+248, 4.27148359e+180]])

In [ ]:
arr10 = np.random.random((2,3))
arr10

array([[0.17717049, 0.8953288 , 0.03143787],
       [0.77880344, 0.83847441, 0.76374622]])

# Numpy Properties and Attributes
1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()