In [ ]:
import numpy as np

In [ ]:
np.random.seed(seed = 1234)

In [ ]:
x = np.array(6)
print("x :",x)
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("x dtype:",x.dtype)


x : 6
x ndim: 0
x shape: ()
x size: 1
x dtype: int64


In [ ]:
x = np.array([i for i in range(1,11)])
print("x :",x)
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("x dtype:",x.dtype)

x : [ 1  2  3  4  5  6  7  8  9 10]
x ndim: 1
x shape: (10,)
x size: 10
x dtype: int64


In [ ]:
d = [[i for i in range(1,5)] for j in range(5,9)]
x = np.array(d)
print("x :",x)
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("x dtype:",x.dtype)

x : [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
x ndim: 2
x shape: (4, 4)
x size: 16
x dtype: int64


In [ ]:
import random as rd
d2 = [[rd.randint(1,9) for i in range(3)] for j in range(5)]
x = np.array(d2)
print("x :",x)
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("x dtype:",x.dtype)

x : [[3 2 5]
 [6 4 3]
 [3 4 4]
 [4 8 6]
 [3 3 7]]
x ndim: 2
x shape: (5, 3)
x size: 15
x dtype: int64


In [ ]:
d3 = [[[rd.randint(1,9) for i in range(3)] for j in range(4)] for k in range(5)]
x = np.array(d3)
print("x :",x)
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("x dtype:",x.dtype)

x : [[[7 3 8]
  [8 3 2]
  [3 6 3]
  [7 2 5]]

 [[8 4 6]
  [2 1 3]
  [5 6 4]
  [6 9 3]]

 [[4 6 1]
  [9 1 3]
  [7 4 4]
  [1 6 3]]

 [[4 8 5]
  [4 8 1]
  [8 2 6]
  [9 7 2]]

 [[6 7 8]
  [7 1 4]
  [3 4 1]
  [4 1 3]]]
x ndim: 3
x shape: (5, 4, 3)
x size: 60
x dtype: int64


In [ ]:
x = np.zeros(5)
print("1d:",x)
y = np.zeros((2,3))
print("2d:",y)
z = np.zeros((2,3,5)) # 3 rows 5 cols of 2 sets
print("3d:",z)

1d: [0. 0. 0. 0. 0.]
2d: [[0. 0. 0.]
 [0. 0. 0.]]
3d: [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [ ]:
x = np.ones(5)
print("1d:",x)
y = np.ones((2,3))
print("2d:",y)
z = np.ones((2,3,5)) # 3 rows 5 cols of 2 sets
print("3d:",z)

1d: [1. 1. 1. 1. 1.]
2d: [[1. 1. 1.]
 [1. 1. 1.]]
3d: [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
x = np.eye(5)
print("1d:",x)

1d: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
x = np.random.random((2,3))
print("1d:",x)
y = np.random.random((2,3,5))
print("nd:",y)

1d: [[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]]
nd: [[[0.27646426 0.80187218 0.95813935 0.87593263 0.35781727]
  [0.50099513 0.68346294 0.71270203 0.37025075 0.56119619]
  [0.50308317 0.01376845 0.77282662 0.88264119 0.36488598]]

 [[0.61539618 0.07538124 0.36882401 0.9331401  0.65137814]
  [0.39720258 0.78873014 0.31683612 0.56809865 0.86912739]
  [0.43617342 0.80214764 0.14376682 0.70426097 0.70458131]]]


# Indexing

In [ ]:
data = [[rd.randint(1,9) for i in range(3)] for j in range(3)]
data = np.array(data)
data

array([[6, 7, 3],
       [7, 3, 9],
       [4, 7, 8]])

In [ ]:
kernel = [[rd.randint(1,9) for i in range(3)] for j in range(3)]
kernel = np.array(kernel)
kernel


array([[7, 5, 9],
       [9, 2, 1],
       [3, 6, 6]])

In [ ]:
sum = np.array(np.add(data,kernel))
sum

array([[13, 12, 12],
       [16,  5, 10],
       [ 7, 13, 14]])

In [ ]:
sub = np.array(np.subtract(data,kernel))
sub

array([[-1,  2, -6],
       [-2,  1,  8],
       [ 1,  1,  2]])

In [ ]:
mul = np.array(np.multiply(data,kernel))
mul

array([[42, 35, 27],
       [63,  6,  9],
       [12, 42, 48]])

In [ ]:
dotproduct = np.array(np.matmul(data,kernel))
dotproduct

array([[114,  62,  79],
       [103,  95, 120],
       [115,  82,  91]])

In [ ]:
dot = np.array(data.dot(kernel))
dot

array([[114,  62,  79],
       [103,  95, 120],
       [115,  82,  91]])

In [ ]:
data

array([[6, 7, 3],
       [7, 3, 9],
       [4, 7, 8]])

In [ ]:
print(np.sum(data))
print(np.sum(data,axis=0))   # sum across the rows(column wise)
print(np.sum(data,axis=1))   # sum across the columns (row wise)

54
[17 17 20]
[16 19 19]


In [ ]:
print(data.min())
print(data.min(axis=1))
print(data.min(axis=0))

3
[3 3 4]
[4 3 3]


In [ ]:
print(data.max())
print(data.max(axis=1))
print(data.max(axis=0))

9
[7 9 8]
[7 7 9]


In [ ]:
x = np.array([1,2])               # [1,2] + 3 = [4,5]
y = np.array(3)                   #         |
z = x+y                           # [1,2] + [3,3] = [4,5]
print(z)

[4 5]


In [ ]:
a = np.array((1,3,7))
b = np.expand_dims(a, axis=1)
c = a+b

c

array([[ 2,  4,  8],
       [ 4,  6, 10],
       [ 8, 10, 14]])

In [ ]:
a = np.array((2,5,8))
b = np.expand_dims(a, axis=1)
c = a+b

c

array([[ 4,  7, 10],
       [ 7, 10, 13],
       [10, 13, 16]])

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print("x: ",x)
print("x.shape: ",x.shape)
y = np.transpose(x)
print("y: ",y)
print("y.shape: ",y.shape)

x:  [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:  [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)


In [ ]:
x = np.array([i for i in range(1,7)])
print(x)

[1 2 3 4 5 6]


In [ ]:
y = np.reshape(x,(2,3))
y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
z = np.reshape(x,(3,2))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = np.random.random((2,3))
x

array([[0.21879211, 0.92486763, 0.44214076],
       [0.90931596, 0.05980922, 0.18428708]])

In [ ]:
y = np.concatenate([x,x],axis =0)
y

array([[0.21879211, 0.92486763, 0.44214076],
       [0.90931596, 0.05980922, 0.18428708],
       [0.21879211, 0.92486763, 0.44214076],
       [0.90931596, 0.05980922, 0.18428708]])

In [ ]:
z = np.concatenate([x,x],axis = 1)
z

array([[0.21879211, 0.92486763, 0.44214076, 0.21879211, 0.92486763,
        0.44214076],
       [0.90931596, 0.05980922, 0.18428708, 0.90931596, 0.05980922,
        0.18428708]])

In [ ]:
yy = np.stack([x,x],axis=0)
yy

array([[[0.21879211, 0.92486763, 0.44214076],
        [0.90931596, 0.05980922, 0.18428708]],

       [[0.21879211, 0.92486763, 0.44214076],
        [0.90931596, 0.05980922, 0.18428708]]])

In [ ]:
x  = np.array([[1,2,3],[4,5,6]])
y = np.expand_dims(x,1)
print(y)
print(y.shape)

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


In [ ]:
x  = np.array([[1,2,3],[4,5,6]])
y = np.expand_dims(x,0)
print(y)
print(y.shape)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [ ]:
x  = np.array([[1,2,3],[4,5,6]])
y = np.expand_dims(x,2)
print(y)
print(y.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [ ]:
x  = np.array([[[1,2,3]],[[4,5,6]]])
y = np.squeeze(x,1)
print(y)
print(y.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
